#!/bin/bash

REQUIRED_WORDS="^(fix|refactor|change|update|add|remove|replace)"
MIN_COMMIT_LENGTH=10
ERROR_TITLE="Git Error"

message=$(cat "${1:?Missing commit message file}")
length=$(echo -n $message | wc -m)

if [ $length -lt $MIN_COMMIT_LENGTH ]; then
  echo $ERROR_TITLE
  echo "The length less than ${MIN_LENGTH}";
  exit 1
fi

if echo "$message" | egrep -iq "$REQUIRED_WORDS" ;
then
  echo "Prehook passed!"
else
  echo $ERROR_TITLE
  echo "Use next pattern - ${REQUIRED_WORDS}"
  exit 1
fi
